language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t mandyzach/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mandyzach/docker-react npm run test

