language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t mandyzach/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mandyzach/docker-react npm run test

deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker"
#  env: "Docker-env"
#  bucket_name: "elasticbeanstalk-us-west-2-123452644674"
#  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"




